export default {
  LANYARD_ROOT: 'lanyard_root',
  VARIABLE_NAME: 'Ketch',
  SHOW_MODAL: 'showModal',
  CLOSE_MODAL: 'closeModal',
  CLOSE: 'close',
  INVOKE_RIGHTS: 'invokeRights',
  UPDATE_CONSENT: 'updateConsent',
  CONFIG_JSON: 'config.json',
  CONSENT_MODAL: 'experiences.consent.modal',
  CONSENT_BANNER: 'experiences.consent.banner',
  PREFERENCE: 'experiences.preference',
  SHORELINE: 'shoreline',
  LANYARD: 'lanyard',
  SEMAPHORE: 'semaphore',
}
