name: Build

on:
  push:
    branches: [ v0 ]
  pull_request:
    branches: [ v0 ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: true
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/cache@v2.1.6
      with:
        path: ~/.npm
        key: v2-node-dep-${{ hashFiles('package-lock.json') }}
        restore-keys: v2-node-dep-
    - run: |
        echo "//registry.npmjs.com/:_authToken=${NPM_TOKEN}" > .npmrc
        echo "@ketch-sdk:registry=https://registry.npmjs.com/" >> .npmrc
        echo "@ketch-com:registry=https://registry.npmjs.com/" >> .npmrc
        echo "always-auth=true" >> .npmrc
    - uses: winchci/actions-node@v14
