apiVersion: v1alpha
kind: playwright
defaults:
  mode: sauce
sauce:
  region: us-west-1
  concurrency: 2 # Controls how many suites are executed at the same time.
  metadata:
    name: Ketch tag
    build: Release $CI_COMMIT_SHORT_SHA
    public: team
docker:
  fileTransfer: copy
playwright:
  version: 1.10.0
image:
  base: saucelabs/stt-playwright-jest-node
  version: latest
rootDir: ./
files:
  - test/
suites:
#  - name: "Firefox using global mode"
#    platformName: "Windows 10"
#    testMatch: '**/*.test.js'
#    params:
#      browserName: "firefox"
#  - name: "Chromium in docker"
#    mode: docker
#    testMatch: '**/*.test.js'
#    params:
#      browserName: "chromium"
  - name: "Chromium in sauce"
    mode: sauce
    platformName: "Windows 10"
    testMatch: '**/*.test.js'
    params:
      browserName: "chromium"
  - name: "Webkit in sauce"
    mode: sauce
    platformName: "Windows 10"
    testMatch: '**/*.test.js'
    params:
      browserName: "webkit"
artifacts:
  download:
    when: always
    match:
      - console.log
    directory: ./artifacts/
